# Generated by Django 4.2.1 on 2023-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[(None, 'choose one of the currencies'), ('Руб', 'Руб.'), ('Usd.', 'Usd.')], max_length=30, verbose_name='Валюта'),
        ),
    ]
